version: "3.3"

services:
  server:
    container_name: simple_chat_back
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3001
    env_file:
      - .env
    volumes:
      - ./:/usr/src/
    command: ["npm", "run", "dev"]
