name: "Heroku deploy"

on:
  push:
    paths:
      - "simple-chat-back/**"
    branches:
      - master

jobs:
  DeployHeroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
        env:
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          PORT: 3000
